Tests/styles us10
MiketheBite/Capstone-project pull request #23
Opened 2023-09-21 09:31 UTC by MiketheBite

2023-09-21 10:53 UTC, Kheirah requested changes
Looks good! Except that the deployment on Vercel fails for some reason. You'll need to resolve that issue before moving on to QA.

2023-09-21 10:53 UTC, Kheirah commented on components/NurseSelection/NurseSelection.js
> +  const filteredNurses = useMemo(() => {
`useMemo` ❤️

2023-09-23 15:39 UTC, donacrisante commented
Hi Miguel,
the styling is great, but the update function doesn't work. When I want to save the changes, the window stays open and the entry is not updated. Please check this.

2023-09-23 19:59 UTC, donacrisante commented
Looks good! Just correct the sentence under "Vacations" with: "Add Vacations, at least two days in a row. For just one day, choose a day off!"

2023-09-23 20:24 UTC, merged